name: Publish Nuget
run-name: ${{ github.actor }} is updating ${{ github.repository }}🚀
on:
  push:
    branches:
      - "release"
jobs:
  create_nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
      
    - name: Pack
      run: dotnet pack ZLoggerColorConsole --configuration Release --output pack/

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}
        if-no-files-found: error
        retention-days: 7
        path: pack/*.nupkg

    - name: Publish Nuget
      run: |
          foreach($file in (Get-ChildItem pack/ -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }
        
    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        content: ""
        title: "New ZLoggerColorConsole Build"
        description: ""
        color: ${{ job.status == 'Success' && '0x00ff00' || '0xff0000' }}
        url: "https://github.com/mic-code/ZLoggerColorConsole"
        username: GitHub Actions